BNO055I2C:
    ros__parameters:
        device: /dev/i2c-0
        address: 40 # 0x28
        frame_id: imu
        data_topic_name: bno055_data
        raw_topic_name: bno055_raw
        mag_topic_name: bno055_mag
        temperature_topic_name: bno055_temperature
        data_status_topic_nametopic_name: bno055_status
